config/routes.rb
Refinery::Core::Engine.routes.draw do
  namespace :mailchimp, :path => '' do
    # Admin routes
    namespace :admin, :path => 'refinery' do
      resources :campaigns do
        member do
          get :send_options
          post :send_test
          post :send_now
          post :schedule
          post :unschedule
        end
      end
    end

    # Frontend routes
    resource :subscriptions, :only => :create

  end
end

app/models/refinery/mailchimp/campaign.rb
module Refinery
  module Mailchimp
    class Campaign < Refinery::Core::BaseModel

      #acts_as_indexed :fields => [:subject, :body]

      self.table_name = 'refinery_mailchimp_campaigns'

      attr_accessible :from_name, :from_email, :subject, :body, :mailchimp_list_id, :mailchimp_template_id, :auto_tweet

      validates_presence_of :subject, :body, :mailchimp_list_id, :from_email, :from_name

      before_save :update_mailchimp_campaign
      before_create :create_mailchimp_campaign
      before_destroy :delete_mailchimp_campaign

      def sent?
        !!sent_at || !!scheduled_at && scheduled_at <= Time.now
      end

      def scheduled?
        !!scheduled_at && scheduled_at > Time.now
      end

      def sent
        sent_at || scheduled_at
      end

      def send_test_to(*emails)
        Refinery::Mailchimp::API.new.campaign_send_test mailchimp_campaign_id, emails
      rescue Hominid::APIError
        false
      end

      def send_now
        success = Refinery::Mailchimp::API.new.campaign_send_now mailchimp_campaign_id
        self.update_attribute :sent_at, Time.now if success
        success
      rescue Hominid::APIError
        false
      end

      def schedule_for(datetime)
        success = Refinery::Mailchimp::API.new.campaign_schedule mailchimp_campaign_id, datetime.utc.strftime("%Y-%m-%d %H:%M:%S")
        self.update_attribute :scheduled_at, datetime if success
        success
      rescue Hominid::APIError
        false
      end

      def unschedule
        success = Refinery::Mailchimp::API.new.campaign_unschedule mailchimp_campaign_id
        self.update_attribute :scheduled_at, nil if success
        success
      rescue Hominid::APIError
        false
      end

      def google_analytics
        RefinerySetting.find_or_set Refinery::Mailchimp::API::GoogleAnalyticsSetting[:name], Refinery::Mailchimp::API::GoogleAnalyticsSetting[:default]
      end

    protected

      def create_mailchimp_campaign
        options = { :subject => subject, :from_email => from_email, :from_name => from_name, :list_id => mailchimp_list_id, :auto_tweet => auto_tweet }
        options[:template_id] = mailchimp_template_id unless mailchimp_template_id.blank?
        
        self.mailchimp_campaign_id = begin
          Refinery::Mailchimp::API.new.campaign_create 'regular', options, { content_key => body }
        rescue Hominid::APIError => e
          halt_with_mailchimp_error e
          return false
        end
      end

      def update_mailchimp_campaign
        return if new_record?

        client = Refinery::Mailchimp::API.new

        options = {:title => :subject, :from_email => :from_email, :from_name => :from_name, :list_id => :mailchimp_list_id, :template_id => :mailchimp_template_id, :content => :body, :auto_tweet => :auto_tweet }
        options.each_pair do |option_name, attribute|
          if changed.include?(attribute.to_s)
            begin 
              success = client.campaign_update mailchimp_campaign_id, option_name, (option_name == :content ? { content_key => body } : self.send(attribute))
            rescue Hominid::APIError => e
              return halt_with_mailchimp_error e
            end
          end
        end
      end

      def delete_mailchimp_campaign
        success = begin
          Refinery::Mailchimp::API.new.campaign_delete mailchimp_campaign_id
        rescue Hominid::APIError
          nil
        end

        return halt_with_mailchimp_error unless success
      end

      def halt_with_mailchimp_error error
        self.errors.add :base, error.message
        return false
      end

      def content_key
        mailchimp_template_id.blank? ? :html : :html_MAIN
      end
    end
  end
end

app/controllers/refinery/mailchimp/admin/campaigns_controller.rb
module Refinery
  module Mailchimp
    module Admin
      class CampaignsController < ::Refinery::AdminController
        respond_to :html
        crudify :'refinery/mailchimp/campaign', :title_attribute => 'subject', :xhr_paging => true, :sortable => false

        rescue_from Refinery::Mailchimp::API::BadAPIKeyError, :with => :need_api_key
        rescue_from Hominid::APIError, :with => :need_api_key

        before_filter :get_mailchimp_assets, :except => :index
        before_filter :find_campaign, :except => [:index, :new, :create]
        before_filter :fully_qualify_links, :only => [:create, :update]

        def new
          @campaign = ::Refinery::Mailchimp::Campaign.new :from_name => ::Refinery::Setting.get_or_set(Refinery::Mailchimp::API::DefaultFromNameSetting[:name], Refinery::Mailchimp::API::DefaultFromNameSetting[:default]),
                                                          :from_email => ::Refinery::Setting.get_or_set(Refinery::Mailchimp::API::DefaultFromEmailSetting[:name], Refinery::Mailchimp::API::DefaultFromEmailSetting[:default])
        end
        
        def create
          @campaign = Campaign.create(params[:campaign])
          
          if @campaign.save
            flash[:notice] = t('refinery.crudify.created', :what => "'#{@campaign.subject}'")
            respond_with(@campaign, :status => :created, :location => refinery.mailchimp_admin_campaigns_path) 
          else
            respond_with(@campaign, :status => :unprocessable_entity) 
          end
        end

        def send_options
        end

        def send_test
          if @campaign.send_test_to params[:email]
            flash[:notice] = t('refinery.mailchimp.admin.campaigns.campaign.send_test_success', :email => params[:email])
            logger.info "Great Successs !! \n \n \n \n"
          else
            flash[:alert] = t('refinery.mailchimp.admin.campaigns.campaign.send_test_failure', :email => params[:email])
            logger.info "Great Failure !! \n \n \n \n"

          end
          sending_redirect_to refinery.mailchimp_admin_campaigns_path
        end

        def send_now
          if @campaign.send_now
            flash[:notice] = t('refinery.mailchimp.admin.campaigns.campaign.send_now_success')
          else
            flash[:alert] = t('refinery.mailchimp.admin.campaigns.campaign.send_now_failure')
          end
          sending_redirect_to refinery.mailchimp_admin_campaigns_path
        end

        def schedule
          if @campaign.schedule_for DateTime.new(*params['date'].values_at('year','month','day','hour','minute').map{|x|x.to_i})
            flash[:notice] = t('refinery.mailchimp.admin.campaigns.campaign.schedule_success')
          else
            flash[:alert] = t('refinery.mailchimp.admin.campaigns.campaign.schedule_failure')
          end
          sending_redirect_to mailchimp_admin_campaigns_path
        end

        def unschedule
          if @campaign.unschedule
            flash[:notice] = t('refinery.mailchimp.admin.campaigns.campaign.unschedule_success')
          else
            flash[:alert] = t('refinery.mailchimp.admin.campaigns.campaign.unschedule_failure')
          end
          sending_redirect_to refinery.mailchimp_admin_campaigns_path
        end

      protected
        def sending_redirect_to(path)
          if from_dialog?
            render :text => "<script>parent.window.location = '#{path}';</script>"
          else
            redirect_to path
          end
        end

        def need_api_key
          msg = t('refinery.mailchimp.admin.campaigns.index.set_api_key')
          flash[:alert] = msg.html_safe
          redirect_to refinery.mailchimp_admin_campaigns_path
        end

        def fully_qualify_links
          #params[:campaign][:body].gsub!(/(href|src)="\//i, %|\\1="#{root_url}|)
        end

        def get_mailchimp_assets
          @lists = client.lists['data']
          @templates = client.templates['user']
        end

        def client
          @client ||= Refinery::Mailchimp::API.new
        end
      end
      end
  end
end

app/views/admin/campaigns/_form.html.erb
<% form_for [:admin, @campaign] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
    :object => @campaign,
    :include_object_name => true
  } %>
  
  <div class='field'>
    <span class='label_with_help'>
      <%= f.label :subject -%>
      <%= refinery_help_tag t('.subject_help') %>
    </span>
    <%= f.text_field :subject, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :body -%>
    <%= f.text_area :body, :rows => 20, :class => 'wymeditor widest' -%>
  </div>

  <div class="hemisquare">
    <h2><%= t('.to_and_from') %></h2>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :to_name, t('.to_name') -%>
        <%= refinery_help_tag t('.to_name_help') %>
      </span>
      <%= f.text_field :to_name %>
    </div>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :from_name, t('.from_name') -%>
        <%= refinery_help_tag t('.from_name_help') %>
      </span>
      <%= f.text_field :from_name %>
    </div>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :from_email, t('.from_email') -%>
        <%= refinery_help_tag t('.from_email_help') %>
      </span>
      <%= f.text_field :from_email %>
    </div>
  </div>

  <div class="hemisquare right_side">
    <h2><%= t('.settings') %></h2>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :mailchimp_list_id, t('.mailchimp_list_id') -%>
        <%= refinery_help_tag t('.mailchimp_list_id_help') %>
      </span>
      <%= f.select :mailchimp_list_id, @lists.collect{ |list| [list['name'], list['id']] } %>
    </div>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :mailchimp_template_id, t('.mailchimp_template_id') -%>
        <%= refinery_help_tag t('.mailchimp_template_id_help') %>
      </span>
      <%= f.select :mailchimp_template_id, @templates.collect{ |template| [template['name'], template['id']] }, :include_blank => true %>
    </div>
    
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :auto_tweet, t('.auto_tweet') -%>
        <%= refinery_help_tag t('.auto_tweet_help') %>
      </span>
      <%= f.check_box :auto_tweet %>
    </div>
  </div>
  
  <div class="clearfix"></div>

  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_subject => t('admin.campaigns.campaign.delete'),
                :delete_confirmation => t('admin.campaigns.campaign.delete_confirmation', :subject => @campaign.subject)
              } %>
<% end -%>

app/views/admin/campaigns/index.html.erb
<div id='actions'>
  <ul>
    <% if Admin::CampaignsController.searchable? %>
      <li>
        <%= render :partial => "/shared/admin/search",
                    :locals => {
                      :url => admin_campaigns_url
                    } %>
      </li>
    <% end %>
    <li>
      <%= link_to t('.create_new'), new_admin_campaign_url,
                   :class => "add_icon" %>
    </li>
  </ul>
</div>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @campaigns.any? %>
      <%= will_paginate @campaigns, :previous_label => '&laquo;', :next_label => '&raquo;' %>
      <ul>
        <%= render :partial => "campaign",
                    :collection => @campaigns %>
      </ul>
      <%= will_paginate @campaigns, :previous_label => '&laquo;', :next_label => '&raquo;' %>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @campaigns.any? %>
      <%= will_paginate @campaigns,
                         :previous_label => '&laquo;',
                         :next_label => '&raquo;' %>

      <%= render :partial => "sortable_list" %>

      <%= will_paginate @campaigns,
                         :previous_label => '&laquo;',
                         :next_label => '&raquo;' %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet') %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>